# Site settings
title: "KITCTF"
baseurl: ""
url: "https://kitctf.de"

github: kitctf
twitter: KITCTF

# Build settings
markdown: kramdown
permalink: /:categories/:title

# Authors
authors:
  saelo:
    url: https://twitter.com/5aelo
  eboda:
    url: https://twitter.com/edgarboda
  niklasb:
    url: https://github.com/niklasb
  mawalu:
    url: https://martinwagner.co
  Liam:
    url: https://wachter-space.de

teamname: KITCTF
